### ISSUE TITLE
CSR cannot be approved as it is not present + PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by shaikhzeeshan1989** [smohith/cp4i-install#1]
[root@dns ~]# oc get csr -o name | xargs oc adm certificate approve
No resources found
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
no kind "CertificateSigningRequest" is registered for version "certificates.k8s.io/v1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

**Comment by egrol** [comment]
@shaikhzeeshan1989 This issue is due to the oc client version difference. If you follow the appendix details to logon to the dns server in order to approve the outstanding CSR's, once you have ssh'd to the dns server run this commands:

oc version

You'll see that the oc client on the dns server is 4.5.x whilst the server is 4.6.x. There is an outstanding bug with Red Hat to allow for backward compatibility to support the API version differences. Essentially this demo should accommodate for the OpenShift version differences.

https://bugzilla.redhat.com/show_bug.cgi?id=1860789

You can on the dns server run this:

wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.6.45/openshift-client-linux.tar.gz
gunzip -d openshift-client-linux.tar.gz
tar -xvf openshift-client-linux.tar

Replace the oc and kubectl versions under /usr/local/bin on the dns server
